"""empty message

Revision ID: e31c562d34c1
Revises: 2207bddd4083
Create Date: 2020-08-17 01:15:15.397365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31c562d34c1'
down_revision = '2207bddd4083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
